name: tripeaks_neue
description: "A Tri Peaks patience (solitaire) game"

publish_to: 'none'

# Don't forget to increase version code (the number that comes after '+')
version: 0.9.3+8

environment:
  sdk: ^3.9.0

dependencies:
  audioplayers: ^6.5.0
  fast_rich_text: ^0.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  intl: any
  logger: ^2.6.1
  mobx: ^2.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.7.0
  build_version: ^2.1.2
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.4
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/tropy.png
    - images/empty.png
    - images/welcome.png
    - images/card_counter_dark.png
    - images/card_counter_light.png
    - sounds/take1.mp3
    - sounds/take2.mp3
    - sounds/take3.mp3
    - sounds/draw.mp3
    - sounds/undo.mp3
    - sounds/error.mp3
    - sounds/start.mp3
    - sounds/win.mp3
    - sounds/gameover.mp3

  fonts:
    - family: Actions
      fonts:
        - asset: fonts/actions.ttf
    - family: Cards
      fonts:
        - asset: fonts/cards.ttf
    - family: Outfit
      fonts:
        - asset: fonts/Outfit-VariableFont_wght.ttf
