import 'package:flutter/widgets.dart';

const double cardSize = 116.0;
const double commonRadius = 12.0;
const commonBorderRadius = BorderRadius.all(Radius.circular(commonRadius));
const double cellPadding = 4.0;
const double pagePadding = 24.0;
const double stockShift = 30.0;
const double buttonSize = 96.0;
const double maxRealButtonSize = 52.0;
const double iconScaleThreshold = 0.4;
const double activeRankSize = 32.0;
const double activeSuitSize = 32.0;
const double inactiveRankSize = 24.0;
const double inactiveSuitSize = 20.0;
const double requiredWidth = 1260;
const double requiredHeight = 600;
const double dropdownItemWidth = 120;
const double maxListWidth = 700;
const double maxRadioWidth = maxListWidth - 32;
