name: "Build for Linux"

# Adapted from https://github.com/ferraridamiano/ConverterNOW/blob/master/.github/workflows/build_deploy.yml

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build Linux app
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-24.04-arm
        include:
        - label: x86_64
          os: ubuntu-latest
        - label: aarch64
          os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Flutter dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa clang \
        cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev

    - name: Install audioplayers dependencies
      run: sudo apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    
    # Use git because subosito/flutter-action does not support arm64 yet (https://github.com/subosito/flutter-action/issues/345)
    - name: Setup Flutter
      run: |
        git clone --branch stable https://github.com/flutter/flutter.git $RUNNER_TEMP/flutter
        cd $RUNNER_TEMP/flutter
        echo "$RUNNER_TEMP/flutter/bin" >> $GITHUB_PATH
        echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

    - name: Flutter version
      run: flutter --version

    - name: Build for linux
      run: flutter build linux --release --no-obfuscate

    - name: Tar linux package
      run: |
        arch=$(ls build/linux)
        tar -C build/linux/$arch/release/bundle -czf tripeaksneue-linux-${{ matrix.label }}.tar.gz .

    - name: Release to GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "tripeaksneue-linux-${{ matrix.label }}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
